//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aronium.Migration.SQLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aronium.Migration.SQLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [Migration](
        ///	[ID] [int] IDENTITY(1,1) NOT NULL,
        ///	[Version] [varchar](20) NOT NULL,
        ///	[Description] [varchar](200) NULL,
        ///	[FileName] [varchar](100) NULL,
        ///	[Date] [datetime] NOT NULL,
        /// CONSTRAINT [PK_Migration] PRIMARY KEY CLUSTERED 
        ///(
        ///	[ID] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY].
        /// </summary>
        internal static string CreateMigrationsTable {
            get {
                return ResourceManager.GetString("CreateMigrationsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(CONVERT(DECIMAL(10,4),[Version])) FROM [Migration].
        /// </summary>
        internal static string GetCurrentVersion {
            get {
                return ResourceManager.GetString("GetCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ID],[Version],[Description],[FileName],[Date] FROM [Migration].
        /// </summary>
        internal static string GetMigrations {
            get {
                return ResourceManager.GetString("GetMigrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Migration] 
        ///(
        ///	[Version],
        ///	[Description],
        ///	[FileName],
        ///	[Date]
        ///) 
        ///VALUES 
        ///(
        ///	REPLACE(SUBSTRING(@scriptName, 0, CHARINDEX(&apos;__&apos;, @scriptName)), &apos;_&apos;, &apos;.&apos;),
        ///	REPLACE(SUBSTRING(@scriptName, CHARINDEX(&apos;__&apos;, @scriptName) + 2, LEN(@scriptName) - (CHARINDEX(&apos;__&apos;, @scriptName) + 5)), &apos;_&apos;, &apos; &apos;),
        ///	@scriptName,
        ///	GETDATE()
        ///).
        /// </summary>
        internal static string LogMigration {
            get {
                return ResourceManager.GetString("LogMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[Migration]&apos;) AND type in (N&apos;U&apos;).
        /// </summary>
        internal static string MigrationTableExists {
            get {
                return ResourceManager.GetString("MigrationTableExists", resourceCulture);
            }
        }
    }
}
